### ISSUE TITLE
Looking for missing placeholder and social media images?

### ISSUE THREAD

**Issue by Stoob** [veda-consulting/uk.co.vedaconsulting.mosaico#340]
After a recent upgrade, Mosaico is showing broken 'placeholder' images for upload in the template and returning errors in the Drupal log such as these:

>https://site.edu/civicrm/mosaico/img?method=placeholder&params=166%2C130

This results in the error seen here.
![errors](https://user-images.githubusercontent.com/1683473/67123467-3efa4e00-f1a5-11e9-9bb2-dac5a6b0b50b.png)

While other 'package' images seem to be 404 missing entirely.

>The requested URL "/sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/packages/mosaico/img/social_def/google+_bw_ok.png" was not found on this server.

>https://site.edu/sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/packages/mosaico/img/social_def/google+_bw_ok.png

Mosiaco is otherwise working.  I am able to upload images of my own, but these placeholder and social media files it is looking for appear to be missing entirely.  Indeed there is no 'img' directory within the package at all, neither in the CiviCRM Mosaico extension nor the Mosaico direct distribution itself: https://github.com/voidlabs/mosaico

I am confused by this.  Why is Mosaico looking for images that no longer exist?  @deepak-srivastava Thanks!

**Comment by mattwire** [comment]
The actual `img` directory is under `packages/mosaico/templates/versafix-1/img`. Some earlier versions had issues with image paths and various solutions were put in place on individual sites including symlinks to get around those issues.  However, those issues were fixed before the stable 2.0 came out. But it could be possible that your templates still have hardcoded paths if they've not been updated (there are versions in the db if you don't go back to the base template).

**Comment by themak1985** [comment]
After encountering this issue after upgrading to 2.2 from 2.1 using the CiviCRM UI on D7 we uninstalled mosaico completely and did a fresh install of 2.2 from the CiviCRM extensions directory. The issue persisted. We uninstalled again and installed 2.1 - all issues were resolved.

Thinking it could be an issue with the upgrade that took place, I upgraded to 2.2 via the UI again - issue returned.  We are staying with 2.1 for now.

Lastly - I created a demo wordpress civicrm site on the same server and installed 2.2 via civicrm ui - there were no issues.

**Comment by aydun** [comment]
It relates to permissions.  `/civicrm/mosaico/img` is handled by `CRM_Mosaico_Utils::processImg()`  For placeholder images it checks for `'access CiviMail', 'create mailings', 'edit message templates'` permissions.  However, `'create mailings'` is not always defined (see `CRM_Mailing_Info:getPermissions()`)

To get things working I removed 'create mailings' from this line: https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/2.x/CRM/Mosaico/Utils.php#L300

I'm not sure why there are extra checks around placeholder images.

**Comment by caracolmzd** [comment]
I found the same as @aydun  and (missing this issue) created #341 yesterday.
https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/341

**Comment by caracolmzd** [comment]
@aydun , are you referring to the check for `if (self::workflowEnabled() || $getAllUnconditionally)` in CRM_Mailing_Info::getPermissions() to explain why 'create mailings' is not always defined?

**Comment by aydun** [comment]
> @aydun , are you referring to the check for `if (self::workflowEnabled() || $getAllUnconditionally)` in CRM_Mailing_Info::getPermissions() to explain why 'create mailings' is not always defined?

@ginkgomzd - Yes! I didn't track back further to find what `workflowEnabled()` relates to, but the effect is that 'create mailings' is only defined in some circumstances.

**Comment by bmango** [comment]
Thank you so much @ginkgomzd for referencing my comment on [Images appear as malformed text
#186](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/186#issuecomment-545928733). 

I was having this same problem. I followed aydun's comment (thank you!) [here](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/340#issuecomment-545849527) removing 'create mailings' in CRM/Mosaico/Utils.php#L300 and now the issue is fixed :). I had spent about 2 days trying to work this out after upgrading Mosaico from 2.1 to 2.2.

**Comment by homotechsual** [comment]
Can we PR this change in? @mattwire any thoughts?

**Comment by aydun** [comment]
> Can we PR this change in?

I didn't PR it since I'm not convinced that is the best fix.  The code has the comment 'Only privileged users can request generation of placeholders'.  Why?  If needed, then should do something conditional around 'create mailings'.

Git suggests @JKingsnorth might know why.

**Comment by caracolmzd** [comment]
The comment does say to me that the permission check is only accomplishing some premature optimization. If we are going to have a permission check at all, why isn't 'Access CiviMail' enough of a restriction?

**Comment by homotechsual** [comment]
Agreed with @ginkgomzd especially seeing as how the Mosaico interface is basically broken without that change or without granting the extra permission which is not always defined.

**Comment by mattwire** [comment]
If one of you @Stoob @ginkgomzd @aydun @bmango can create a suitable PR I'm happy to review and merge - @JKingsnorth any thoughts on this?

**Comment by caracolmzd** [comment]
I think someone just needs to make the call on what the change should be:
 A) remove 'create mailings
 B) only check 'access CiviMail'
 C) remove the permission check.

Here is the patch I used to get my client going:
``` shell
--- CRM/Mosaico/Utils.php	2019-10-23 15:53:28.212222456 -0400
+++ CRM/Mosaico/Utils.php.hack	2019-10-23 15:53:46.488871005 -0400
@@ -297,7 +297,7 @@
         case 'placeholder':
 
           // Only privileged users can request generation of placeholders
-          if (!CRM_Core_Permission::check(['access CiviMail', 'create mailings', 'edit message templates'])) {
+          if (!CRM_Core_Permission::check(['access CiviMail', 'edit message templates'])) {
             CRM_Utils_System::permissionDenied();
           }
```

**Comment by deepak-srivastava** [comment]
IMO any of those permissions should be valid for placeholders. And probably intention might have been to use OR instead of AND.

And in that case the code should be 
`[['access CiviMail', 'create mailings', 'edit message templates']]`
instead of
`['access CiviMail', 'create mailings', 'edit message templates']`

based on https://github.com/civicrm/civicrm-core/blob/master/CRM/Core/Permission.php#L91

**Comment by JKingsnorth** [comment]
> I didn't PR it since I'm not convinced that is the best fix. The code has the comment 'Only privileged users can request generation of placeholders'. Why? If needed, then should do something conditional around 'create mailings'.
> 
> Git suggests @JKingsnorth might know why.

Hi! Yes, placeholder generation should only be a privileged thing. Because otherwise it would be possible for unprivileged (anonymous) users to request high volumes of placeholder generation on the sever. Since this can be quite resource-intensive for larger images, it poses a risk of opening up denial-of-service attacks.

I hadn't realised that 'create mailings' wasn't always set. Why would it not be set? Sorry I haven't dug into it, but I though that was just a Civi core permission? Surely that points to a deeper issue?

But either way, @deepak-srivastava is right, I think this should have been an 'OR' check - because I was just reusing the same permissions as here (if I remember rightly): https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/174f3766bee4db79bade6e073e079ed6b645243e/xml/Menu/mosaico.xml#L27

Apologies for the unintended consequences =]

**Comment by homotechsual** [comment]
#342 changes the `AND` to `OR`.

**Comment by caracolmzd** [comment]
Do we need another issue to look into other undiscovered issues around checks for 'create mailings'? Whom is familiar with the code referenced here:
https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/340#issuecomment-545916953

**Comment by homotechsual** [comment]
> > @aydun , are you referring to the check for `if (self::workflowEnabled() || $getAllUnconditionally)` in CRM_Mailing_Info::getPermissions() to explain why 'create mailings' is not always defined?
> 
> @ginkgomzd - Yes! I didn't track back further to find what `workflowEnabled()` relates to, but the effect is that 'create mailings' is only defined in some circumstances.

So the `workflowEnabled()` check returns true when the CMS is Drupal and Rules is enabled. See: https://github.com/civicrm/civicrm-core/blob/d4af0c989cafde710c4a1addd7973c6de95c1e60/settings/Mailing.setting.php#L69

**Comment by caracolmzd** [comment]
@MikeyMJCO so... that seems like useful information, but I cant make the leap to what should happen next.
brain slows down this time of day.

SO.. I think we've confirmed the permission does not always exist. So the follow-up should be maybe to create issues in both mosaico and core to search for permission checks for 'create mailing' and ensure they are all conditional or "OR'd"?

**Comment by homotechsual** [comment]
> @MikeyMJCO so... that seems like useful information, but I cant make the leap to what should happen next.
> brain slows down this time of day.
> 
> SO.. I think we've confirmed the permission does not always exist. So the follow-up should be maybe to create issues in both mosaico and core to search for permission checks for 'create mailing' and ensure they are all conditional or "OR'd"?

The PR addresses the only occurance of this in Mosaico.

All uses in Core are either "OR" or single checks for the `Create Mailings` permission within the conditional logic. 

I think we can chalk this one upto a simple missing OR that should have been in place.

**Comment by deepak-srivastava** [comment]
I came across a Joomla install with mosaico v2.3 installed and patch #342 applied, but still failing with the permission error. 

Dug a bit deeper to find out what's happening.

Turns out unlike Drupal (and like Wordpress), for Joomla installs there could be two types of URLs:
1. Backend URL - https://example.org/administrator/?option=com_civicrm&task=civicrm/mosaico/img&method=placeholder&params=166%2C130
2. Frontend URL - https://example.org/index.php?option=com_civicrm&task=civicrm/mosaico/img&method=placeholder&params=166%2C130

Now civicrm/mosaico/img is a <is_public> url and therefore generates a frontend url like:
https://example.org/index.php?option=com_civicrm&task=civicrm/mosaico/img&method=placeholder&params=166%2C130

And even for admins, permission check ends up checking if "public" user group (frontend users) have one of those permissions ('access CiviMail', 'create mailings', 'edit message templates'), which is unlikely. And therefore fails.

I suspect problem might be same on Wordpress (haven't tested).

While the motive behind the permission seems to be valid i.e placeholders are an admin thing, the intention doesn't seem to work for above cases.

An alternative soultion could be to separate out placeholder urls from that of other types (resize, cover). May be with a wrapper. And in the xml structure declare it to be non-frontend and requiring designated permissions. 
(The route may encounter some hurdles.)

It might be a good idea to rollback the permission check as a temporary measure.

**Comment by homotechsual** [comment]
By "rollback" do you mean remove or revert the patch - reverting the patch will break placeholders for all sites.

Agree that we need to find a solution for this.

**Comment by deepak-srivastava** [comment]
By rollback i mean - not having the permission check at all. Assuming it would take some time to come out with alternative solution?

**Comment by JKingsnorth** [comment]
Why are placeholder images being displayed to front-end users though? I'm confused. Surely all placeholders would be replaced out, before a mailing is sent? Or are the images 'hidden' in the template, but the URLs to the images stay in the email?

**Comment by deepak-srivastava** [comment]
Missing placeholder images is a problem for user creating the template using the editor, even if the user is an admin. Functionality wise it works fine when you upload an image, but gives an impression that something is not right and broken.

Here is a screenshot to better explain the problem.

![image](https://user-images.githubusercontent.com/3448551/68308274-7f623300-00a4-11ea-9b77-56a09297c374.png)

**Comment by Stoob** [comment]
Thank you for the screenshot @deepak-srivastava.  Your assessment of the issue is correctly in-line with my concerns in my original posting.  While it is possible to upload images during composition, the 'broken image' icons of the placeholders are disorienting, and depending on the browser it is more or less easy to click to upload.

**Comment by JKingsnorth** [comment]
OK, thanks for the helpful screenshot, I understand the issue here.

But I'm not sure why it's happening, surely the permissions check still goes through to processImg, case placeholder:

https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/6bce989eea02d7b9a687b4c2cf2181789b4d0797/CRM/Mosaico/Utils.php#L297-L305

And at this point the logged in user must have one of those permissions, since they are in the editing interface for a mosaico template? Why would it be doing a permissions check against a different user, just because it's a public URL, or is that how the Joomla version works?

**Comment by larssandergreen** [comment]
I just upgraded to 2.3 (from 2.1) and am still experiencing this issue on Drupal. It's bad enough that for an image-only block sometimes the height of the image block is zero or very thin, making it very difficult to delete the block and pretty much impossible to upload your own image (at least in Chrome).

From the logs:
Location | https://secure.wildsight.ca/civicrm/mosaico/img?method=placeholder&params=570%2C200
-- | --
https://secure.wildsight.ca/civicrm/mosaico/iframe?snippet=1
Error: Call to undefined function Intervention\Image\Gd\imagettfbbox() in Intervention\Image\Gd\Font->getBoxSize() (line 85 of /var/www/html/sites/default/civicrm/extensions/uk.co.vedaconsulting.mosaico/vendor/intervention/image/src/Intervention/Image/Gd/Font.php).

**Comment by homotechsual** [comment]
Hi @larssg-wildsight your issue appears to be a different issue to the permissions issue being discussed in this issue. Can you move your post to a new issue as it's not permissions related.

M

**Comment by adixon** [comment]
@larssg-wildsight @MikeyMJCO 
confirmed, Lars' issue is similar to this one:
https://github.com/Intervention/image/issues/484
Looks like the gd / server requirements have changed in a recent version of mosaico and need documentation, or else it's there and I need to read it.

As an aside - I would note that the issue title is going to generate a fair amount of noise - this symptom can be caused by a great number of different underlying issues.

**Comment by larssandergreen** [comment]
Thanks @adixon. We were on 2.1 for a while and this issue only started recently, so it must be something more complex than just the requirements of a particular version. In any case, now resolved.

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
