### ISSUE TITLE
Packages are missing since update to V2.8

### ISSUE THREAD

**Issue by netzih** [veda-consulting/uk.co.vedaconsulting.mosaico#474]
Just updated mosaico to 2.8 and I can't use it anymore,
Status page has an error that says ```Mosaico: Packages are missing
Mosaico requires dependencies in its "packages" folder. Please consult the README.md for current installation instructions.```
When clicking on new mailing in the menu I get ```Mosaico cannot be displayed because this system does not meet all requirements.
For details, check the System Status.```

This seems to be new since updating mosaico to 2.8.

**Comment by MegaphoneJon** [comment]
Some troubleshooting questions:
* Is the packages subfolder present in the mosaico extension folder?  
* Do the permissions/file owner match the mosaico folder?
* What's the URL you downloaded version 2.8 from?

**Comment by netzih** [comment]
Hi,

1. No. I do not see the packages folder under uploads/civicrm/ext/uk.co.vedaconsulting.mosaico
2. Permissions seem to be correct.
3. I downloaded it originally directly from the extensions page within CiviCRM and upgraded it from there as well.
 
![Capture](https://user-images.githubusercontent.com/48005023/142276180-e9c45624-1e74-4aa2-9509-fb14036f4978.PNG)
(I am attaching a screenshot of the contents in the above directory here)

**Comment by MegaphoneJon** [comment]
OK, I can confirm the same thing.  I also notice that 2.8 is not yet available for download at https://civicrm.org/extensions/email-template-builder, which suggests that the release notification may be premature.

Mosaico contains other sub-applications ("packages") that aren't stored in this git repo because they'd get out-of-date.  The `package.json` file specifies what those packages are.  If you have NodeJS and npm installed, you can run `npm install` which will download the necessary packages - at least in theory, I'm getting an error.  Otherwise we'll have to wait for the .zip file to be updated.

**Comment by mattwire** [comment]
See https://lab.civicrm.org/infra/extdir/-/issues/5  The feed should not have published the release - the fully working / packaged version *is* now available here: https://civicrm.org/extensions/email-template-builder because I've just published it, hopefully the feed will update soon to point to that.

**Comment by johngehrig** [comment]
@MegaphoneJon I encountered the same issue by updating Mosaico to 2.8 using the "CiviCRM Extensions" page installation link. I believe I have resolved the issue with the update by downloading the correctly packaged files from the CiviCRM Extensions page (https://civicrm.org/extensions/email-template-builder), and then extracting and uploading the files to the server (https://docs.civicrm.org/sysadmin/en/latest/customize/extensions/#installing-a-new-extension) -- I renamed the directory associated with the initial update "uk.co.vedaconsulting.mosaico BROKEN" before uploading the new files and the Mosiaco interface is loading properly within CiviCRM.

@mattwire I still get an error when vistiting the Flexailer Settings page: Administer > CiviMail > Flexmailer Settings:

>  Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
> QuickForm Error: unregistered element

Any ideas?

**Comment by johngehrig** [comment]
@mattwire I was able to get the Flexmailer Settings page to load by visiting and re-saving the other various CiviMail settings:

Administer > CiviMail > Mailer Settings
Administer > CiviMail > CiviMail Component Settings
Administer > CiviMail > Mosaico Settings

The only issue I have now is that the previously saved email templates do not display the image placeholder blocks within Mosaico, and, when I insert a new image block, the placeholder still does not appear but a text link to upload an image does appear:

![11-17-2021 5-21-17 PM](https://user-images.githubusercontent.com/41501085/142291885-84c1a2e8-3bdf-45fd-acd4-b12203c0fff1.png)

**Comment by johngehrig** [comment]
@mattwire I was able to completely resolve all issues with Mosaico by reverting to PHP 7.3 -- I had switched the site to PHP 7.4 when I first encountered errors with the Mosaico 2.8 update but switching back to PHP 7.3 fixed the image display issues with the Imagick Graphics Driver.

**Comment by alexmarketaccess** [comment]
We updated Mosaico to 2.8 on our WordPress site (civiCRM 5.38.0) and got the same error wrt to "Mosaico cannot be displayed because this system does not meet all requirements." I tried the same steps as @johngehrig (download new full package, rename existing one, extra newly uploaded package to ext folder)...  but it didn't make a difference -- still getting the same error. 

Any suggestions how to resolve?

**Comment by MegaphoneJon** [comment]
@alexmarketaccess Can you check and provide the answers to the questions I asked in my first comment on this issue?

**Comment by netzih** [comment]
I disabled mosaico, uninstalled it, deleted the mosaico directory from the extension folder and reinstalled it.
I was working on a clean install with no prior emails so it was OK, not sure how it would affect those with existing prior emails sent through mosaico.

**Comment by alexmarketaccess** [comment]
@MegaphoneJon Some good news! In the time between my post and your response, I was able to resolve the issue: basically the same thing you did, but I had to copy and paste the packages folder into my existing 2.8 mosaico install, and all is good,.

**Comment by yurg** [comment]
Same here on March 17, 2002 with **_Mosaico requires dependencies in its "packages" folder. Please consult the README.md for current installation instructions._** even if there is FlexMailer  5.47.2 (core one) installed. Any hint?

**Comment by MegaphoneJon** [comment]
@yurg Please open a new issue?  In that issue, please give the answers to the questions I asked above:
* Is the packages subfolder present in the mosaico extension folder?
* Do the permissions/file owner match the mosaico folder?
* What's the URL you downloaded version 2.8 from?

**Comment by yurg** [comment]
@MegaphoneJon Thank you for stepping in!
 - No, it is not: not quite sure if we need another copy of tinymce plugins and fontawesome but it feels like the subfolder presense proves the extension has been downloaded from a proper source. 
 - Yes, it does.
 - I believe I've tried to install it from extensions directory lately (wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fextensions&reset=1&action=browse) Please see below: would the error message be a bit confusing? It says `"Extension Upgrade Failed. You will not be able to install/upgrade Mosaico until you have installed the org.civicrm.flexmailer extension."` but flexmailer is NOT installed, it just sits in the available extensions list and it comes from the core extensions directory.
 
![image](https://user-images.githubusercontent.com/273282/159087660-3062c240-c8e4-4967-a344-3dea856aeb06.png)
