### ISSUE TITLE
Angular Errors on New Mailing with v2.9.1645644008 and Civi Core 5.46.2

### ISSUE THREAD

**Issue by pbarmak** [veda-consulting/uk.co.vedaconsulting.mosaico#494]
I'm not sure what the root cause is, but whenever we create a New Mailing using the latest Mosaico release and latest Civi core release, we see the following console errors. We cannot select a Group in the Recipients field, it just hangs (spinning wheel) and gives additional console errors. This happens in both Mosaico and Traditional mailings when the Mosaico extension is enabled. I'm guessing there is some incompatibility between the extension and maybe Civi 5.46.2, but not sure. I've cleared caches, cleared the dyn folder, etc, but we still see the errors.

If I disable the Mosaico extension, I can create new traditional mailings without any issues; groups for recipients come up, etc.

This is the first error (on New Mailing page load):
```
Error: [$interpolate:interr] [http://errors.angularjs.org/1.8.2/$interpolate/interr?p0=%7B…inActionLabel)%7D%7D&p1=TypeError%3A%20text%20is%20undefined](http://errors.angularjs.org/1.8.2/$interpolate/interr?p0=%7B%7Bts(mainActionLabel)%7D%7D&p1=TypeError%3A%20text%20is%20undefined)
    Angular 8
[angular.js:15697:15](https://xxx/sites/all/modules/civicrm/bower_components/angular/angular.js)
    Angular 27
    jQuery 7
    api3 crm.ajax.js:118
    Angular 16
    jQuery 7
    api3 crm.ajax.js:118
    Angular 22
    jQuery 5
```

This is the second error (on page load):
```
ReferenceError: assignment to undeclared variable date
    link Angular
    jQuery 6
[angular.js:15697:15](https://xxx/sites/all/modules/civicrm/bower_components/angular/angular.js)
    Angular 14
    jQuery 7
    api3 crm.ajax.js:118
    Angular 16
    jQuery 7
    api3 crm.ajax.js:118
    Angular 22
    jQuery 5
```
And this is the error we get when we click in the Recipients box to pick a group:
```
Uncaught ReferenceError: assignment to undeclared variable results
    results Angular
    success select2.min.js:30
    jQuery 7
    api3 crm.ajax.js:118
    transport Angular
    i select2.min.js:32
    setTimeout handler*C/< select2.min.js:29
    updateResults select2.min.js:110
    opening select2.min.js:180
    open select2.min.js:87
    initContainer select2.min.js:178
    bind select2.min.js:56
    jQuery 8
    initContainer select2.min.js:178
    init select2.min.js:57
    select2 select2.min.js:206
    jQuery 2
    select2 select2.min.js:206
    Angular 10
[angular-modules.038920480d3a401d51d63297f33ab985.js:18003:29](https://xxx/sites/default/files/civicrm/persist/contribute/dyn/angular-modules.038920480d3a401d51d63297f33ab985.js?r830i8)
    results Angular
    success select2.min.js:30
    jQuery 7
    api3 crm.ajax.js:118
    transport Angular
    i select2.min.js:32
    (Async: setTimeout handler)
    C select2.min.js:29
    updateResults select2.min.js:110
    opening select2.min.js:180
    open select2.min.js:87
    initContainer select2.min.js:178
    bind select2.min.js:56
    jQuery 8
    initContainer select2.min.js:178
    init select2.min.js:57
    select2 select2.min.js:206
    jQuery 2
    select2 select2.min.js:206
    Angular 10
```

**Comment by MegaphoneJon** [comment]
This is an asset caching issue - clearing cache doesn't seem to clear the asset cache.  Is this a problem with Mosaico or core?  Not sure, maybe @colemanw has a thought.

To fix this, go to **Administer menu » System Settings » Debugging and Error Handling**, then set *Asset Caching* to **Disabled**.  This should fix the issue, and when you put it back to **Auto** (which you should, for performance reasons) the problem should stay fixed.

**Comment by MegaphoneJon** [comment]
And perhaps I spoke too soon - this fixed it on one site for me but not a second.

**Comment by pbarmak** [comment]
> And perhaps I spoke too soon - this fixed it on one site for me but not a second.

I can verify that clearing the asset cache did not fix it on our site either. I followed the steps, same errors show up.

**Comment by MegaphoneJon** [comment]
What's notable is that on the two sites (so far) I've observed the problem, my development site, with an identical codebase, isn't exhibiting the issue.  There's a remote possibility there's a difference in the database, but it's almost certainly an issue related to the caching.  It seems like a file isn't getting loaded, or is loaded out of order, or the wrong version is loaded - unfortunately `date` and `results` are pretty generic variable names so I've yet to track down the file in question.

**Comment by MegaphoneJon** [comment]
OK - I'm able to reliably get the recipient widget to succeed when *Enable Debugging* is set to **Yes**, and fail again when it's set to **No** - even on sites where I never touched the asset caching. @pbarmak that's not an ideal solution, but please a) report if it works for you, b) it's a temporary solution if you're desperate.

**Comment by pbarmak** [comment]
@MegaphoneJon I can confirm that turning on Enable Debugging does work on our site. It could be a temp solution (though yes, you are right, not ideal).

**Comment by MegaphoneJon** [comment]
I'm not done digging, but I'm not sure if I'll be able to finish today.  However I've found:
With debug on:
* `angular.js` is loaded.
* `<civiroot>/ang/resetLocationProviderHashPrefix.js` is loaded next (this is never loaded with debug off).
* `<civiroot>/js/crm-angularjs-loader.js` is loaded next, followed by a bunch of js files in `<civiroot>/ang`.

With debug off:
* `angular.min.js` is loaded (but confirmed to still be 1.8.2, same as angular.js).
* `angular-modules.js` is loaded next (this isn't loaded with debug on).
* `<civiroot>/js/crm-angularjs-loader.js` is loaded next.

**Comment by MegaphoneJon** [comment]
OK, this is caused by this change:
```diff
--- crmMosaico.ang.php  2022-03-02 14:05:00.836792514 -0500
+++ crmMosaico.ang.php.29       2022-03-02 11:53:57.143417893 -0500
@@ -4,7 +4,7 @@
 // http://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_angularModules
 
 $result = [
-  'requires' => ['crmUi', 'crmUtil', 'ngRoute', 'crmMailing'],
+  'requires' => ['crmUi', 'crmUtil', 'ngRoute', 'crmMailing', 'crmDialog'],
   'js' =>
   [
     0 => 'ang/crmMosaico.js',
```

This change is in #478 - reverting just this line without reverting anything else fixes the problem.  @monishdeb do you have any thoughts?  I'll post replication steps in a new comment.

**Comment by MegaphoneJon** [comment]
### Replication Steps
* Install Mosaico on a fresh Civi install.  Ensure debugging is off.
* Create a new mailing (Mosaico or traditional, doesn't matter).
* Attempt to use the *Recipients* widget.  It never populates.

This doesn't occur when debugging is on, or when `crmDialog` isn't specified in `crmMosaico.ang.php` (see my last comment).

**Comment by colemanw** [comment]
`crmDialog` was only recently added to core, in 5.46 with commit https://github.com/civicrm/civicrm-core/pull/22229/commits/138b573379151444139ae6d15f1691f5b98fb4d2
Are you perhaps using an earlier version of Civi?

**Comment by MegaphoneJon** [comment]
@colemanw No, I replicated this on both 5.46 and master.

**Comment by colemanw** [comment]
@MegaphoneJon I think I figured it out: https://github.com/civicrm/civicrm-core/pull/22879

**Comment by colemanw** [comment]
Pr has been merged. This issue can be closed.
